"""add bias vote system and user verification

Revision ID: 2f9a1257f294
Revises: cc831318bbbf
Create Date: 2026-02-22 23:40:12.921924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9a1257f294'
down_revision = 'cc831318bbbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bone_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('vote_left', sa.Integer(), nullable=True),
    sa.Column('vote_center', sa.Integer(), nullable=True),
    sa.Column('vote_right', sa.Integer(), nullable=True),
    sa.Column('vote_total', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('bias_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bias', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'article_id', name='unique_user_article_vote')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('verify_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('verify_badge', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('bones', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_bias_votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accurate_votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accurate_votes')
        batch_op.drop_column('total_bias_votes')
        batch_op.drop_column('bones')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verify_badge')
        batch_op.drop_column('verify_category')
        batch_op.drop_column('verify_tier')

    op.drop_table('bias_votes')
    op.drop_table('news_articles')
    op.drop_table('bone_transactions')
    # ### end Alembic commands ###
