"""add youtube_url to posts

Revision ID: cc831318bbbf
Revises: 046c3c48ff0b
Create Date: 2026-02-18 21:11:22.579234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc831318bbbf'
down_revision = '046c3c48ff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('left_count', sa.Integer(), nullable=True),
    sa.Column('right_count', sa.Integer(), nullable=True),
    sa.Column('bias_ratio', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bias_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bias_metrics_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_bias_metrics_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('youtube_url')

    with op.batch_alter_table('bias_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bias_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_bias_metrics_keyword'))

    op.drop_table('bias_metrics')
    # ### end Alembic commands ###
